#!/bin/bash
# FastestJSONInTheWest Environment Setup Script
# Generated by EnvironmentAgent

set -e

echo "Setting up FastestJSONInTheWest development environment..."

# Detect platform
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    PLATFORM="linux"
    if command -v apt-get &> /dev/null; then
        PACKAGE_MANAGER="apt"
    elif command -v yum &> /dev/null; then
        PACKAGE_MANAGER="yum"
    elif command -v dnf &> /dev/null; then
        PACKAGE_MANAGER="dnf"
    else
        echo "Unsupported Linux distribution"
        exit 1
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    PLATFORM="macos"
    PACKAGE_MANAGER="brew"
else
    echo "Unsupported platform: $OSTYPE"
    exit 1
fi

echo "Detected platform: $PLATFORM with package manager: $PACKAGE_MANAGER"

# Install dependencies based on platform
if [[ "$PACKAGE_MANAGER" == "apt" ]]; then
    sudo apt-get update
    sudo apt-get install -y wget curl git build-essential python3 python3-pip
    
    # Add LLVM repository
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    echo "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-21 main" | sudo tee /etc/apt/sources.list.d/llvm.list
    
    sudo apt-get update
    sudo apt-get install -y clang-21 clang++-21 clang-tools-21 clang-tidy-21 clang-format-21
    sudo apt-get install -y libopenmpi-dev openmpi-bin
    sudo apt-get install -y libzmq3-dev libcppzmq-dev
    sudo apt-get install -y libgtest-dev valgrind

elif [[ "$PACKAGE_MANAGER" == "brew" ]]; then
    brew install llvm@21 cmake open-mpi zmq cppzmq googletest valgrind
fi

# Install Python dependencies
pip3 install ansible pyyaml

# Validate installation
echo "Validating installation..."
clang++-21 --version || echo "Warning: clang++-21 not found"
cmake --version || echo "Warning: cmake not found"
mpirun --version || echo "Warning: mpirun not found"

echo "Environment setup complete!"
